spring:
  profiles:
    active: test
  datasource:
    url: jdbc:postgresql://192.168.137.134:5432/opengis
    username: postgres
    password: postgres

logging:
  path: ./logs/spatial-query
  level:
    com.wyb.spatialquery: warn
    org.springframework.web: warn

swagger2:
  enabled: false