server:
  port: 9000
spring:
  application:
    name: spatial-query
  datasource:
    driver-class-name: org.postgresql.Driver
    dbcp2:
      max-idle: 10
      max-wait-millis: 8000
      max-open-prepared-statements: 2
      validation-query: select 1
      max-total: 15
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
logging:
  file:
    max-history: 10

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

swagger2:
  title: 空间查询服务
  version: 1.0
  groupName: 个人
  author: wyblzu
  description: PostgreSQL构建的空间查询服务
  basePackage: com.wyb.spatialquery
---
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://192.168.137.134:5432/opengis
    username: postgres
    password: postgres

logging:
  level:
    com.wyb.spatialquery: debug
    org.springframework.web: debug

swagger2:
  enabled: true
---
spring:
  profiles:
    active: test
  datasource:
    url: jdbc:postgresql://192.168.137.134:5432/opengis
    username: postgres
    password: postgres

logging:
  path: ./logs/spatial-query
  level:
    com.wyb.spatialquery: warn
    org.springframework.web: warn

swagger2:
  enabled: false
---
spring:
  profiles:
    active: prod
  devtools:
    restart:
      enabled: true

  datasource:
    url: jdbc:postgresql://192.168.137.134:5432/opengis
    username: postgres
    password: postgres

logging:
  path: ./logs/spatial-query
  level:
    com.wyb.spatialquery: warn
    org.springframework.web: warn

swagger2:
  enabled: false